name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tensorflow-gpu=2.8.0
  - numpy
  - scikit-learn
  - matplotlib
  - pillow
  - pyyaml
  - ipython
  - jupyter
  - pip
  - pip:
    - tensorflow-datasets