name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pytorch=2.1.0
  - torchvision
  - cudatoolkit = 12.6  
  - tensorboard
  - pip
  - pip:
      - matplotlib
